spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8082

kafka:
  address: localhost:29092
  topics: my_topic
  groupId: 1
